
version: '3.1'

services:
  jrtb-db-dev:
    image: mysql:5.7
    restart: always

    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'

      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3366:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'